name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: ok-nick/setup-aftman@v0.3.0
        name: Install aftman
        with:
          token: ${{ SECRETS.GITHUB_TOKEN }}

      - name: Lint
        run: |
          selene ./src

  style:
    name: Styling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: StyLua
        uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check ./src

  docs:
    name: Build Document
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4

      - name: Install Moonwave
        run: npm i -g moonwave

      - name: Build
        run: moonwave build --publish
